version: "3.8"
services:
  app:
    build: .
    command: pnpm dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  test:
    build: .
    command: pnpm test
    #volumes:
    #  - .:/app
