version: "3.8"

services:
  app:
    build: .
    command: pnpm dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # segurança extra caso use outra lib que depende disso
